export const metadata = {
  title: "Privacy Policy | PEC",
  description: "Privacy policy for PEC apps and services."
};

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-white">
      <div className="container mx-auto px-6 py-16 max-w-4xl">
        <h1 className="text-3xl md:text-4xl font-serif font-semibold text-gray-900">
          Privacy Policy
        </h1>
        <p className="mt-3 text-sm text-gray-600">
          Effective date: April 3, 2026
        </p>

        <section className="mt-10 space-y-4 text-gray-700 leading-relaxed">
          <p>
            PEC Petrochemical Engineering &amp; Construction ("PEC", "we", "our") operates
            mobile and web applications for project execution, team communication, and attendance
            tracking. This policy explains how we collect, use, and protect information.
          </p>
        </section>

        <section className="mt-10 space-y-3 text-gray-700">
          <h2 className="text-xl font-semibold text-gray-900">Information We Collect</h2>
          <p>
            We collect information you provide directly and information generated by your use
            of the app. This may include:
          </p>
          <p>
            Account and profile details such as name, phone number, role, and organization.
          </p>
          <p>
            Project activity data such as chat messages, attendance entries, and work updates.
          </p>
          <p>
            Device data required for security and diagnostics, such as device identifiers and
            app version.
          </p>
          <p>
            Optional media you submit, such as photos captured or uploaded for project updates
            or attendance verification.
          </p>
          <p>
            Location data if you grant permission and if attendance or site verification
            features require it.
          </p>
        </section>

        <section className="mt-10 space-y-3 text-gray-700">
          <h2 className="text-xl font-semibold text-gray-900">How We Use Information</h2>
          <p>
            We use information to operate the service, authenticate users, maintain project
            records, and provide collaboration features. We also use data to improve performance,
            troubleshoot issues, and meet legal or contractual obligations.
          </p>
        </section>

        <section className="mt-10 space-y-3 text-gray-700">
          <h2 className="text-xl font-semibold text-gray-900">Sharing and Disclosure</h2>
          <p>
            We do not sell personal information. We may share data with trusted service providers
            (such as hosting, authentication, and analytics) strictly to operate the service.
            We may also disclose information if required by law or to protect the rights and
            safety of users and the organization.
          </p>
        </section>

        <section className="mt-10 space-y-3 text-gray-700">
          <h2 className="text-xl font-semibold text-gray-900">Data Storage and Security</h2>
          <p>
            Data is stored in secure cloud infrastructure with access controls. We use reasonable
            administrative and technical safeguards to protect information. No method of storage
            or transmission is 100% secure, but we continuously improve protections.
          </p>
        </section>

        <section className="mt-10 space-y-3 text-gray-700">
          <h2 className="text-xl font-semibold text-gray-900">Retention</h2>
          <p>
            We retain data as long as needed for business operations, legal requirements, and
            contractual obligations with organizations using the service.
          </p>
        </section>

        <section className="mt-10 space-y-3 text-gray-700">
          <h2 className="text-xl font-semibold text-gray-900">Your Choices</h2>
          <p>
            You can update certain profile details in the app. You may also revoke optional
            permissions (such as camera or location) through your device settings, though some
            features may not work without them.
          </p>
        </section>

        <section className="mt-10 space-y-3 text-gray-700">
          <h2 className="text-xl font-semibold text-gray-900">Contact</h2>
          <p>
            For privacy questions or requests, contact us at info@pecengg.com.
          </p>
        </section>
      </div>
    </div>
  );
}
